mz_get_started:
  outputs:
    dev:
      type: materialize
      host: materialized
      port: 6875
      user: materialize
      password: password
      database: materialize
      cluster: default
      schema: qck
  target: dev